//! Bulk operations for EdiDocument entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateEdiDocumentDto;
use crate::application::service::EdiDocumentService;
use crate::domain::entity::EdiDocument;

/// Bulk operation handler for EdiDocument entities.
///
/// Wraps `EdiDocumentService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type EdiDocumentBulkService = GenericBulkService<EdiDocument, CreateEdiDocumentDto, EdiDocumentService>;

// <<< CUSTOM
// END CUSTOM
