//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod edi_document_bulk;
pub mod trading_partner_bulk;

pub use edi_document_bulk::EdiDocumentBulkService;
pub use trading_partner_bulk::TradingPartnerBulkService;

// <<< CUSTOM
// END CUSTOM
