//! Bulk operations for TradingPartner entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateTradingPartnerDto;
use crate::application::service::TradingPartnerService;
use crate::domain::entity::TradingPartner;

/// Bulk operation handler for TradingPartner entities.
///
/// Wraps `TradingPartnerService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type TradingPartnerBulkService = GenericBulkService<TradingPartner, CreateTradingPartnerDto, TradingPartnerService>;

// <<< CUSTOM
// END CUSTOM
