//! EdiDocument DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::EdiDocument;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EdiDirection;
use crate::domain::entity::EdiDocType;
use crate::domain::entity::EdiStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new EdiDocument
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateEdiDocumentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "partner_id")]
    pub partner_id: Uuid,
    #[serde(alias = "doc_type")]
    pub doc_type: EdiDocType,
    pub direction: EdiDirection,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "control_number")]
    pub control_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "business_key")]
    pub business_key: String,
    pub status: EdiStatus,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub payload: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mapped_ref_type")]
    pub mapped_ref_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mapped_ref_id")]
    pub mapped_ref_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "acknowledged_at")]
    pub acknowledged_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a EdiDocument
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateEdiDocumentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "partner_id")]
    pub partner_id: Uuid,
    #[serde(alias = "doc_type")]
    pub doc_type: EdiDocType,
    pub direction: EdiDirection,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "control_number")]
    pub control_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "business_key")]
    pub business_key: String,
    pub status: EdiStatus,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub payload: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mapped_ref_type")]
    pub mapped_ref_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "mapped_ref_id")]
    pub mapped_ref_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "acknowledged_at")]
    pub acknowledged_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a EdiDocument
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchEdiDocumentDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "partner_id")]
    pub partner_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "doc_type")]
    pub doc_type: Option<EdiDocType>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub direction: Option<EdiDirection>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "control_number")]
    pub control_number: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "business_key")]
    pub business_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<EdiStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub payload: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "mapped_ref_type")]
    pub mapped_ref_type: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "mapped_ref_id")]
    pub mapped_ref_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "error_detail")]
    pub error_detail: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "acknowledged_at")]
    pub acknowledged_at: Option<DateTime<Utc>>,
}

impl PatchEdiDocumentDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.partner_id.is_some() || self.doc_type.is_some() || self.direction.is_some() || self.control_number.is_some() || self.business_key.is_some() || self.status.is_some() || self.payload.is_some() || self.mapped_ref_type.is_some() || self.mapped_ref_id.is_some() || self.error_detail.is_some() || self.acknowledged_at.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for EdiDocument entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EdiDocumentResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub partner_id: Uuid,
    pub doc_type: EdiDocType,
    pub direction: EdiDirection,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub control_number: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub business_key: String,
    pub status: EdiStatus,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub payload: String,
    pub mapped_ref_type: Option<String>,
    pub mapped_ref_id: Option<Uuid>,
    pub error_detail: Option<String>,
    pub acknowledged_at: Option<DateTime<Utc>>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for EdiDocument entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EdiDocumentListResponseDto {
    /// List of items
    pub items: Vec<EdiDocumentResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl EdiDocumentListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<EdiDocumentResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct EdiDocumentSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub partner_id: Uuid,
    pub doc_type: EdiDocType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<EdiDocument> for EdiDocumentResponseDto {
    fn from(entity: EdiDocument) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            partner_id: entity.partner_id,
            doc_type: entity.doc_type,
            direction: entity.direction,
            control_number: entity.control_number,
            business_key: entity.business_key,
            status: entity.status,
            payload: entity.payload,
            mapped_ref_type: entity.mapped_ref_type,
            mapped_ref_id: entity.mapped_ref_id,
            error_detail: entity.error_detail,
            acknowledged_at: entity.acknowledged_at,
            metadata: entity.metadata,
        }
    }
}

impl From<EdiDocument> for EdiDocumentSummaryDto {
    fn from(entity: EdiDocument) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            partner_id: entity.partner_id,
            doc_type: entity.doc_type,
            created_at,
        }
    }
}

impl From<CreateEdiDocumentDto> for EdiDocument {
    fn from(dto: CreateEdiDocumentDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            partner_id: dto.partner_id,
            doc_type: dto.doc_type,
            direction: dto.direction,
            control_number: dto.control_number,
            business_key: dto.business_key,
            status: dto.status,
            payload: dto.payload,
            mapped_ref_type: dto.mapped_ref_type,
            mapped_ref_id: dto.mapped_ref_id,
            error_detail: dto.error_detail,
            acknowledged_at: dto.acknowledged_at,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&EdiDocument> for EdiDocumentResponseDto {
    fn from(entity: &EdiDocument) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            partner_id: entity.partner_id.clone(),
            doc_type: entity.doc_type.clone(),
            direction: entity.direction.clone(),
            control_number: entity.control_number.clone(),
            business_key: entity.business_key.clone(),
            status: entity.status.clone(),
            payload: entity.payload.clone(),
            mapped_ref_type: entity.mapped_ref_type.clone(),
            mapped_ref_id: entity.mapped_ref_id.clone(),
            error_detail: entity.error_detail.clone(),
            acknowledged_at: entity.acknowledged_at.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateEdiDocumentDto> for EdiDocument {
    fn from_create_dto(dto: CreateEdiDocumentDto) -> backbone_core::ServiceResult<Self> {
        Ok(EdiDocument::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateEdiDocumentDto> for EdiDocument {
    fn apply_update(mut self, dto: UpdateEdiDocumentDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.partner_id = dto.partner_id;
        self.doc_type = dto.doc_type;
        self.direction = dto.direction;
        self.control_number = dto.control_number;
        self.business_key = dto.business_key;
        self.status = dto.status;
        self.payload = dto.payload;
        self.mapped_ref_type = dto.mapped_ref_type;
        self.mapped_ref_id = dto.mapped_ref_id;
        self.error_detail = dto.error_detail;
        self.acknowledged_at = dto.acknowledged_at;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to EdiDocument here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
