//! TradingPartner DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::TradingPartner;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::EdiFormat;
use crate::domain::entity::PartnerDirection;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new TradingPartner
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateTradingPartnerDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "partner_code")]
    pub partner_code: String,
    pub format: EdiFormat,
    #[serde(alias = "partner_direction")]
    pub partner_direction: PartnerDirection,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a TradingPartner
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateTradingPartnerDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "partner_code")]
    pub partner_code: String,
    pub format: EdiFormat,
    #[serde(alias = "partner_direction")]
    pub partner_direction: PartnerDirection,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "is_active")]
    pub is_active: bool,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a TradingPartner
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchTradingPartnerDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "partner_code")]
    pub partner_code: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub format: Option<EdiFormat>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "partner_direction")]
    pub partner_direction: Option<PartnerDirection>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "is_active")]
    pub is_active: Option<bool>,
}

impl PatchTradingPartnerDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.partner_code.is_some() || self.format.is_some() || self.partner_direction.is_some() || self.is_active.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for TradingPartner entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TradingPartnerResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub partner_code: String,
    pub format: EdiFormat,
    pub partner_direction: PartnerDirection,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub is_active: bool,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for TradingPartner entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TradingPartnerListResponseDto {
    /// List of items
    pub items: Vec<TradingPartnerResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl TradingPartnerListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<TradingPartnerResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct TradingPartnerSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: String,
    pub partner_code: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<TradingPartner> for TradingPartnerResponseDto {
    fn from(entity: TradingPartner) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            partner_code: entity.partner_code,
            format: entity.format,
            partner_direction: entity.partner_direction,
            is_active: entity.is_active,
            metadata: entity.metadata,
        }
    }
}

impl From<TradingPartner> for TradingPartnerSummaryDto {
    fn from(entity: TradingPartner) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            name: entity.name,
            partner_code: entity.partner_code,
            created_at,
        }
    }
}

impl From<CreateTradingPartnerDto> for TradingPartner {
    fn from(dto: CreateTradingPartnerDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            name: dto.name,
            partner_code: dto.partner_code,
            format: dto.format,
            partner_direction: dto.partner_direction,
            is_active: dto.is_active,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&TradingPartner> for TradingPartnerResponseDto {
    fn from(entity: &TradingPartner) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            name: entity.name.clone(),
            partner_code: entity.partner_code.clone(),
            format: entity.format.clone(),
            partner_direction: entity.partner_direction.clone(),
            is_active: entity.is_active.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateTradingPartnerDto> for TradingPartner {
    fn from_create_dto(dto: CreateTradingPartnerDto) -> backbone_core::ServiceResult<Self> {
        Ok(TradingPartner::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateTradingPartnerDto> for TradingPartner {
    fn apply_update(mut self, dto: UpdateTradingPartnerDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.name = dto.name;
        self.partner_code = dto.partner_code;
        self.format = dto.format;
        self.partner_direction = dto.partner_direction;
        self.is_active = dto.is_active;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to TradingPartner here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
