//! Domain policies
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod edi_document_domain_policy;
pub mod trading_partner_domain_policy;

pub use edi_document_domain_policy::EdiDocumentDomainPolicy;
pub use trading_partner_domain_policy::TradingPartnerDomainPolicy;

// <<< CUSTOM
// END CUSTOM
