//! Application service for EdiDocument entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `edi_document_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateEdiDocumentDto, UpdateEdiDocumentDto};
use crate::domain::entity::EdiDocument;
use crate::infrastructure::persistence::EdiDocumentRepository;

/// Application service for EdiDocument entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `edi_document_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct EdiDocumentServiceCustom {
///     inner: Arc<EdiDocumentService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type EdiDocumentService = GenericCrudService<
    EdiDocument,
    CreateEdiDocumentDto,
    UpdateEdiDocumentDto,
    EdiDocumentRepository,
>;

// <<< CUSTOM
// END CUSTOM
