//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod edi_document_service;
pub mod trading_partner_service;

// <<< CUSTOM
pub mod edi_ports;
pub mod edi_events;
pub mod edi_write_service;
// END CUSTOM

pub use edi_document_service::EdiDocumentService;
pub use trading_partner_service::TradingPartnerService;
// <<< CUSTOM
pub use edi_ports::{MapAck, MapRejected, MapRequest, MappingPort};
pub use edi_events::{EdiDocumentMapped, EdiEvent, EdiEventSink, LoggingSink};
pub use edi_write_service::{EdiError, EdiWriteService, InboundDoc, NewPartner, ReceiveOutcome};
// END CUSTOM