//! Application service for TradingPartner entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `trading_partner_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateTradingPartnerDto, UpdateTradingPartnerDto};
use crate::domain::entity::TradingPartner;
use crate::infrastructure::persistence::TradingPartnerRepository;

/// Application service for TradingPartner entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `trading_partner_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct TradingPartnerServiceCustom {
///     inner: Arc<TradingPartnerService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type TradingPartnerService = GenericCrudService<
    TradingPartner,
    CreateTradingPartnerDto,
    UpdateTradingPartnerDto,
    TradingPartnerRepository,
>;

// <<< CUSTOM
// END CUSTOM
