-- EdiDocument Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the edi.edi_documents table.
-- Customize this file to add your initial data.

-- INSERT INTO edi.edi_documents (
--     id,
--     company_id,
--     partner_id,
--     doc_type,
--     direction,
--     control_number,
--     business_key,
--     status,
--     payload,
--     mapped_ref_type,
--     mapped_ref_id,
--     error_detail,
--     acknowledged_at,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO edi.edi_documents (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

