-- Audit Triggers Migration for edi module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: EdiDocument (edi.edi_documents)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION edi.edi_documents_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS edi_documents_insert_audit ON edi.edi_documents;
CREATE TRIGGER edi_documents_insert_audit BEFORE INSERT ON edi.edi_documents
    FOR EACH ROW EXECUTE FUNCTION edi.edi_documents_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS edi_documents_update_audit ON edi.edi_documents;
CREATE TRIGGER edi_documents_update_audit BEFORE UPDATE ON edi.edi_documents
    FOR EACH ROW EXECUTE FUNCTION edi.edi_documents_audit_timestamp();

-- ==============================================================================
-- Table: TradingPartner (edi.trading_partners)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION edi.trading_partners_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS trading_partners_insert_audit ON edi.trading_partners;
CREATE TRIGGER trading_partners_insert_audit BEFORE INSERT ON edi.trading_partners
    FOR EACH ROW EXECUTE FUNCTION edi.trading_partners_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS trading_partners_update_audit ON edi.trading_partners;
CREATE TRIGGER trading_partners_update_audit BEFORE UPDATE ON edi.trading_partners
    FOR EACH ROW EXECUTE FUNCTION edi.trading_partners_audit_timestamp();

