-- Migration: Create edi_documents table
-- Generated by metaphor-schema

-- Create edi_doc_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'edi_doc_type') THEN
        CREATE TYPE edi_doc_type AS ENUM ('purchase_order', 'invoice', 'ship_notice', 'functional_ack');
    END IF;
END
$$;

-- Create edi_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'edi_direction') THEN
        CREATE TYPE edi_direction AS ENUM ('inbound', 'outbound');
    END IF;
END
$$;

-- Create edi_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'edi_status') THEN
        CREATE TYPE edi_status AS ENUM ('received', 'mapped', 'acknowledged', 'generated', 'sent', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS edi;

CREATE TABLE IF NOT EXISTS edi.edi_documents (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    partner_id UUID NOT NULL,
    doc_type edi_doc_type NOT NULL,
    direction edi_direction NOT NULL,
    control_number TEXT NOT NULL,
    business_key TEXT NOT NULL,
    status edi_status NOT NULL DEFAULT 'received',
    payload TEXT NOT NULL,
    mapped_ref_type TEXT,
    mapped_ref_id UUID,
    error_detail TEXT,
    acknowledged_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_edi_documents_partner_id_direction_business_key ON edi.edi_documents (partner_id, direction, business_key);

CREATE INDEX IF NOT EXISTS idx_edi_documents_company_id_status ON edi.edi_documents (company_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_edi_documents_metadata_gin ON edi.edi_documents USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_edi_documents_metadata_deleted_at ON edi.edi_documents ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_edi_documents_metadata_created_at ON edi.edi_documents ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_edi_documents_metadata_updated_at ON edi.edi_documents ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION edi.edi_documents_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS edi_documents_insert_audit ON edi.edi_documents;
CREATE TRIGGER edi_documents_insert_audit BEFORE INSERT ON edi.edi_documents
    FOR EACH ROW EXECUTE FUNCTION edi.edi_documents_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS edi_documents_update_audit ON edi.edi_documents;
CREATE TRIGGER edi_documents_update_audit BEFORE UPDATE ON edi.edi_documents
    FOR EACH ROW EXECUTE FUNCTION edi.edi_documents_audit_timestamp();
