-- Migration: Create trading_partners table
-- Generated by metaphor-schema

-- Create edi_format enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'edi_format') THEN
        CREATE TYPE edi_format AS ENUM ('custom_json', 'x12', 'edifact', 'csv');
    END IF;
END
$$;

-- Create partner_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'partner_direction') THEN
        CREATE TYPE partner_direction AS ENUM ('both', 'inbound', 'outbound');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS edi;

CREATE TABLE IF NOT EXISTS edi.trading_partners (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    name TEXT NOT NULL,
    partner_code TEXT NOT NULL,
    format edi_format NOT NULL DEFAULT 'custom_json',
    partner_direction partner_direction NOT NULL DEFAULT 'both',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_trading_partners_company_id_partner_code ON edi.trading_partners (company_id, partner_code);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_trading_partners_metadata_gin ON edi.trading_partners USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_trading_partners_metadata_deleted_at ON edi.trading_partners ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_trading_partners_metadata_created_at ON edi.trading_partners ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_trading_partners_metadata_updated_at ON edi.trading_partners ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION edi.trading_partners_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS trading_partners_insert_audit ON edi.trading_partners;
CREATE TRIGGER trading_partners_insert_audit BEFORE INSERT ON edi.trading_partners
    FOR EACH ROW EXECUTE FUNCTION edi.trading_partners_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS trading_partners_update_audit ON edi.trading_partners;
CREATE TRIGGER trading_partners_update_audit BEFORE UPDATE ON edi.trading_partners
    FOR EACH ROW EXECUTE FUNCTION edi.trading_partners_audit_timestamp();
