-- Enum types for edi module
-- Generated by metaphor-schema

-- Create edi_doc_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'edi_doc_type') THEN
        CREATE TYPE edi_doc_type AS ENUM ('purchase_order', 'invoice', 'ship_notice', 'functional_ack');
    END IF;
END
$$;

-- Create edi_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'edi_direction') THEN
        CREATE TYPE edi_direction AS ENUM ('inbound', 'outbound');
    END IF;
END
$$;

-- Create edi_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'edi_status') THEN
        CREATE TYPE edi_status AS ENUM ('received', 'mapped', 'acknowledged', 'generated', 'sent', 'failed');
    END IF;
END
$$;

-- Create edi_format enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'edi_format') THEN
        CREATE TYPE edi_format AS ENUM ('custom_json', 'x12', 'edifact', 'csv');
    END IF;
END
$$;

-- Create partner_direction enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'partner_direction') THEN
        CREATE TYPE partner_direction AS ENUM ('both', 'inbound', 'outbound');
    END IF;
END
$$;

