-- Company RLS fence for edi module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for edi.edi_documents
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE edi.edi_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE edi.edi_documents FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS edi_documents_company_isolation ON edi.edi_documents;
CREATE POLICY edi_documents_company_isolation ON edi.edi_documents
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for edi.trading_partners
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE edi.trading_partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE edi.trading_partners FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS trading_partners_company_isolation ON edi.trading_partners;
CREATE POLICY trading_partners_company_isolation ON edi.trading_partners
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

