//! Domain events for EdiDocument entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::EdiDocument;

/// Domain events for EdiDocument — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<EdiDocument>)` variant.
pub type EdiDocumentEvent = CrudEvent<EdiDocument>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for EdiDocument events.
pub type EdiDocumentEventPublisher = Arc<dyn CrudEventPublisher<EdiDocument> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopEdiDocumentEventPublisher = NoOpCrudEventPublisher<EdiDocument>;
