//! Event handler trait for EdiDocument events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::EdiDocumentEvent;

/// Event handler for EdiDocument events.
/// Implement this trait to react to EdiDocument lifecycle events.
pub trait EdiDocumentEventHandler: EventHandler<EdiDocumentEvent> {}
