//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod edi_document_events;
pub mod edi_document_event_handlers;
pub mod trading_partner_events;
pub mod trading_partner_event_handlers;

pub use edi_document_events::{EdiDocumentEvent, EdiDocumentEventPublisher, NoopEdiDocumentEventPublisher};
pub use edi_document_event_handlers::EdiDocumentEventHandler;
pub use trading_partner_events::{TradingPartnerEvent, TradingPartnerEventPublisher, NoopTradingPartnerEventPublisher};
pub use trading_partner_event_handlers::TradingPartnerEventHandler;

// <<< CUSTOM
// END CUSTOM
