//! Event handler trait for TradingPartner events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::TradingPartnerEvent;

/// Event handler for TradingPartner events.
/// Implement this trait to react to TradingPartner lifecycle events.
pub trait TradingPartnerEventHandler: EventHandler<TradingPartnerEvent> {}
