//! Domain events for TradingPartner entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::TradingPartner;

/// Domain events for TradingPartner — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<TradingPartner>)` variant.
pub type TradingPartnerEvent = CrudEvent<TradingPartner>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for TradingPartner events.
pub type TradingPartnerEventPublisher = Arc<dyn CrudEventPublisher<TradingPartner> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopTradingPartnerEventPublisher = NoOpCrudEventPublisher<TradingPartner>;
