//! Event subscriber type aliases for Edi module
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::GenericEventSubscriber;

use crate::domain::event::EdiDocumentEvent;
use crate::domain::event::TradingPartnerEvent;

/// Subscriber for EdiDocument events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type EdiDocumentEventSubscriber = GenericEventSubscriber<EdiDocumentEvent>;

/// Subscriber for TradingPartner events.
///
/// Register handlers via `GenericEventSubscriber::new(topics, handlers)`.
pub type TradingPartnerEventSubscriber = GenericEventSubscriber<TradingPartnerEvent>;

// <<< CUSTOM
// END CUSTOM
