//! TradingPartner seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial TradingPartner data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// TRADINGPARTNER SEEDER
// ============================================================================

/// Seeder for trading_partner
pub struct SeedTradingPartnerSeeder;

impl SeedTradingPartnerSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedTradingPartnerSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedTradingPartnerSeeder {
    fn name(&self) -> &'static str {
        "SeedTradingPartnerSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if edi.trading_partners table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM edi.trading_partners")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/trading_partner_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM edi.trading_partners")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

