//! Repository trait for EdiDocument aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the EdiDocument aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{EdiDocument, EdiDirection, EdiDocType, EdiStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EdiDocumentPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl EdiDocumentPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct EdiDocumentPaginatedResult {
    pub data: Vec<EdiDocument>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct EdiDocumentFilter {
    pub company_id: Option<Uuid>,
    pub partner_id: Option<Uuid>,
    pub doc_type: Option<EdiDocType>,
    pub direction: Option<EdiDirection>,
    pub control_number: Option<String>,
    pub business_key: Option<String>,
    pub status: Option<EdiStatus>,
    pub payload: Option<String>,
    pub mapped_ref_type: Option<String>,
    pub mapped_ref_id: Option<Uuid>,
    pub error_detail: Option<String>,
}

impl EdiDocumentFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.partner_id.is_some() || self.doc_type.is_some() || self.direction.is_some() || self.control_number.is_some() || self.business_key.is_some() || self.status.is_some() || self.payload.is_some() || self.mapped_ref_type.is_some() || self.mapped_ref_id.is_some() || self.error_detail.is_some()
    }
}

/// Repository trait for EdiDocument aggregate
///
/// This trait defines the persistence contract for EdiDocument entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait EdiDocumentRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new edi_document entity
    async fn save(&self, entity: &EdiDocument) -> Result<EdiDocument>;

    /// Find edi_document by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<EdiDocument>>;

    /// Find all edi_document entities
    async fn find_all(&self) -> Result<Vec<EdiDocument>>;

    /// Update edi_document by ID
    async fn update(&self, id: &str, entity: &EdiDocument) -> Result<Option<EdiDocument>>;

    /// Delete edi_document by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List edi_document with pagination
    async fn list(&self, params: EdiDocumentPaginationParams) -> Result<EdiDocumentPaginatedResult>;

    /// List edi_document with pagination and filters
    async fn list_with_filters(&self, params: EdiDocumentPaginationParams, filters: EdiDocumentFilter) -> Result<EdiDocumentPaginatedResult>;

    /// Count all edi_document entities
    async fn count(&self) -> Result<u64>;

    /// Count edi_document entities matching filters
    async fn count_with_filters(&self, filters: EdiDocumentFilter) -> Result<u64>;

    /// Check if edi_document exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete edi_document by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted edi_document by ID
    async fn restore(&self, id: &str) -> Result<Option<EdiDocument>>;

    /// List soft-deleted edi_document entities
    async fn list_deleted(&self, params: EdiDocumentPaginationParams) -> Result<EdiDocumentPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save edi_document entities
    async fn bulk_save(&self, entities: &[EdiDocument]) -> Result<Vec<EdiDocument>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
