//! Repository traits
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DDD Repository traits - define persistence contracts for aggregates.
//! Implementations should be in the infrastructure layer.


pub mod edi_document_repository;
pub mod trading_partner_repository;

// Re-exports
pub use edi_document_repository::{
    EdiDocumentRepository,
    EdiDocumentPaginationParams,
    EdiDocumentPaginatedResult,
    EdiDocumentFilter,
};
pub use trading_partner_repository::{
    TradingPartnerRepository,
    TradingPartnerPaginationParams,
    TradingPartnerPaginatedResult,
    TradingPartnerFilter,
};
