//! Repository trait for TradingPartner aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the TradingPartner aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{TradingPartner, EdiFormat, PartnerDirection};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TradingPartnerPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl TradingPartnerPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct TradingPartnerPaginatedResult {
    pub data: Vec<TradingPartner>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct TradingPartnerFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub partner_code: Option<String>,
    pub format: Option<EdiFormat>,
    pub partner_direction: Option<PartnerDirection>,
    pub is_active: Option<bool>,
}

impl TradingPartnerFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.partner_code.is_some() || self.format.is_some() || self.partner_direction.is_some() || self.is_active.is_some()
    }
}

/// Repository trait for TradingPartner aggregate
///
/// This trait defines the persistence contract for TradingPartner entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait TradingPartnerRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new trading_partner entity
    async fn save(&self, entity: &TradingPartner) -> Result<TradingPartner>;

    /// Find trading_partner by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<TradingPartner>>;

    /// Find all trading_partner entities
    async fn find_all(&self) -> Result<Vec<TradingPartner>>;

    /// Update trading_partner by ID
    async fn update(&self, id: &str, entity: &TradingPartner) -> Result<Option<TradingPartner>>;

    /// Delete trading_partner by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List trading_partner with pagination
    async fn list(&self, params: TradingPartnerPaginationParams) -> Result<TradingPartnerPaginatedResult>;

    /// List trading_partner with pagination and filters
    async fn list_with_filters(&self, params: TradingPartnerPaginationParams, filters: TradingPartnerFilter) -> Result<TradingPartnerPaginatedResult>;

    /// Count all trading_partner entities
    async fn count(&self) -> Result<u64>;

    /// Count trading_partner entities matching filters
    async fn count_with_filters(&self, filters: TradingPartnerFilter) -> Result<u64>;

    /// Check if trading_partner exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete trading_partner by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted trading_partner by ID
    async fn restore(&self, id: &str) -> Result<Option<TradingPartner>>;

    /// List soft-deleted trading_partner entities
    async fn list_deleted(&self, params: TradingPartnerPaginationParams) -> Result<TradingPartnerPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save trading_partner entities
    async fn bulk_save(&self, entities: &[TradingPartner]) -> Result<Vec<TradingPartner>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
