//! Repository for EdiDocument entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written EdiDocument SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Tenancy (ADR-0029): the SQL here carries no tenant key. The scoped helpers ride the
//! request-dedicated connection when the composing service bound one (its fence variables govern
//! what the RLS layer accepts) and fall back to plain pool access otherwise.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<EdiDocument, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use crate::domain::entity::EdiDocument;

/// Table name for EdiDocument entities
pub const TABLE_NAME: &str = "edi.edi_documents";

/// Repository for EdiDocument entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct EdiDocumentRepository(
    backbone_orm::GenericCrudRepository<EdiDocument, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for EdiDocumentRepository {
    type Target = backbone_orm::GenericCrudRepository<EdiDocument, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl EdiDocumentRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an inbound-document dedup claim writes.
pub struct NewInboundDocRow<'a> {
    pub id: Uuid,
    pub partner_id: Uuid,
    pub doc_type: &'a str,
    pub control_number: &'a str,
    pub business_key: &'a str,
    /// Bound to the `payload` column — the partner's raw document, as the original write did.
    pub raw: &'a str,
}

/// A redelivered document's current state, as seen by the dedup re-read. Carries the full row the
/// re-drive path needs (control number + stored payload), not just the outcome triple.
pub struct DocOutcomeRow {
    pub id: Uuid,
    pub status: String,
    pub mapped_ref_id: Option<Uuid>,
    pub control_number: String,
    pub payload: String,
}

/// The pre-update state captured by the acknowledge CTE — carries the 997 polarity the consumer
/// needs to generate the wire ack.
pub struct AckRow {
    pub partner_id: Uuid,
    pub control_number: String,
    pub accepted: bool,
    pub error_detail: Option<String>,
}

/// Hand-written EdiDocument SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl EdiDocumentRepository {
    /// Claim the (partner, inbound, business_key) dedup slot. `Ok(None)` = this business document was
    /// already received (a partner retransmission) and the caller must re-read the original.
    ///
    /// Runs outside a transaction on the pool via the scoped-execute helper: it rides the
    /// request-dedicated connection when the composing service bound a scope (its WITH CHECK governs
    /// the insert) and falls back to a plain pool insert otherwise.
    pub async fn claim_inbound(
        &self,
        pool: &PgPool,
        d: &NewInboundDocRow<'_>,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        let row = backbone_orm::org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO edi.edi_documents
                     (id, partner_id, doc_type, direction, control_number, business_key, status, payload)
                   VALUES ($1,$2,$3::edi_doc_type,'inbound'::edi_direction,$4,$5,'received'::edi_status,$6)
                   ON CONFLICT (partner_id, direction, business_key) DO NOTHING
                   RETURNING id"#,
            )
            .bind(d.id).bind(d.partner_id).bind(d.doc_type)
            .bind(d.control_number).bind(d.business_key).bind(d.raw),
        )
        .await?;
        Ok(row.map(|r| r.get("id")))
    }

    /// Re-read the original after a losing dedup claim. Rides the scoped-execute helper, as above —
    /// under a composing service's fence another unit's rows are simply not matched. The
    /// (partner_id, direction, business_key) unique guarantees at most one row.
    pub async fn fetch_inbound_by_business_key(
        &self,
        pool: &PgPool,
        partner_id: Uuid,
        business_key: &str,
    ) -> Result<DocOutcomeRow, sqlx::Error> {
        let row = backbone_orm::org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, status::text AS status, mapped_ref_id, control_number, payload
                   FROM edi.edi_documents
                   WHERE partner_id=$1 AND direction='inbound'::edi_direction AND business_key=$2"#,
            )
            .bind(partner_id).bind(business_key),
        )
        .await?;
        match row {
            Some(r) => Ok(DocOutcomeRow {
                id: r.get("id"), status: r.get("status"), mapped_ref_id: r.get("mapped_ref_id"),
                control_number: r.get("control_number"), payload: r.get("payload"),
            }),
            None => Err(sqlx::Error::RowNotFound),
        }
    }

    /// Record a successful mapping to an internal document. State-guarded on `received` (a fresh
    /// claim) or `failed` (a re-drive that was just reset back to `received`, or racing one).
    ///
    /// Takes the CALLER'S connection so this and the outbox stage commit as one unit. The caller
    /// has already propagated the ambient org scope onto it (`bind_org_scope_on`) when one was
    /// bound — don't re-bind here.
    ///
    /// Returns rows-affected: the caller stages/publishes its outbox event ONLY on `true`, which
    /// kills the duplicate event when two retransmissions race the same re-drive.
    pub async fn mark_mapped(
        &self,
        conn: &mut sqlx::PgConnection,
        document_id: Uuid,
        mapped_ref_type: &str,
        mapped_ref_id: Uuid,
    ) -> Result<bool, sqlx::Error> {
        let res = sqlx::query(
            r#"UPDATE edi.edi_documents
               SET status='mapped'::edi_status, mapped_ref_type=$2, mapped_ref_id=$3, error_detail=NULL
               WHERE id=$1 AND status IN ('received'::edi_status,'failed'::edi_status)"#,
        )
        .bind(document_id).bind(mapped_ref_type).bind(mapped_ref_id)
        .execute(conn)
        .await?;
        Ok(res.rows_affected() == 1)
    }

    /// Record a mapping rejection. State-guarded on `received`. Same caller-owned-tx contract and
    /// rows-affected semantics as [`Self::mark_mapped`].
    pub async fn mark_failed(
        &self,
        conn: &mut sqlx::PgConnection,
        document_id: Uuid,
        error_detail: &str,
    ) -> Result<bool, sqlx::Error> {
        let res = sqlx::query(
            r#"UPDATE edi.edi_documents SET status='failed'::edi_status, error_detail=$2
               WHERE id=$1 AND status='received'::edi_status"#,
        )
        .bind(document_id).bind(error_detail)
        .execute(conn)
        .await?;
        Ok(res.rows_affected() == 1)
    }

    /// Re-open a document that never completed mapping — crash-stranded `received` with no
    /// mapped_ref, or any prior `failed` — so a retransmission can settle it. Refreshes the stored
    /// envelope from the incoming copy. `false` = the row is settled (`mapped`/`acknowledged`, or
    /// already re-driven past the guard): the caller must return the stored outcome untouched.
    ///
    /// Runs on the pool through the scoped-execute helper: under a composing service's fence the
    /// request connection's variables govern the row; with no scope bound this is a plain update.
    pub async fn reset_for_redrive(
        &self,
        pool: &PgPool,
        document_id: Uuid,
        incoming_control_number: &str,
        incoming_raw: &str,
    ) -> Result<bool, sqlx::Error> {
        let res = backbone_orm::org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE edi.edi_documents
                   SET status='received'::edi_status, control_number=$2, payload=$3,
                       error_detail=NULL, mapped_ref_type=NULL, mapped_ref_id=NULL
                   WHERE id=$1
                     AND status IN ('received'::edi_status,'failed'::edi_status)
                     AND mapped_ref_id IS NULL"#,
            )
            .bind(document_id).bind(incoming_control_number).bind(incoming_raw),
        )
        .await?;
        Ok(res.rows_affected() == 1)
    }

    /// Acknowledge a mapped/failed document, returning its PRE-update state. Idempotent: `Ok(None)` when
    /// the document is absent or not in an acknowledgeable state.
    ///
    /// ID-only: no tenant argument. `fetch_optional_row_scoped` means it rides a connection carrying
    /// the composing service's fence variables, so another unit's document simply is not found. A
    /// caller running with no scope bound (an ack job / an event-driven sink outside a request)
    /// fails closed on a fenced deployment and returns `Ok(None)`.
    pub async fn acknowledge(
        &self,
        pool: &PgPool,
        document_id: Uuid,
    ) -> Result<Option<AckRow>, sqlx::Error> {
        let row = backbone_orm::org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"WITH d AS (
                     SELECT id, partner_id, control_number, (status='mapped'::edi_status) AS accepted, error_detail
                     FROM edi.edi_documents
                     WHERE id=$1 AND status IN ('mapped'::edi_status,'failed'::edi_status)
                     FOR UPDATE)
                   UPDATE edi.edi_documents e SET status='acknowledged'::edi_status, acknowledged_at=now()
                   FROM d WHERE e.id = d.id
                   RETURNING d.partner_id, d.control_number, d.accepted, d.error_detail"#,
            )
            .bind(document_id),
        )
        .await?;
        Ok(row.map(|r| AckRow {
            partner_id: r.get("partner_id"), control_number: r.get("control_number"),
            accepted: r.get("accepted"), error_detail: r.get("error_detail"),
        }))
    }
}

backbone_core::impl_crud_repository!(EdiDocumentRepository, EdiDocument, soft_delete);
