//! Repository implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Uses backbone-orm's `DatabaseOperations<T>` trait.

mod edi_document_repository;
mod trading_partner_repository;

// Custom persistence modules
// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use edi_document_repository::EdiDocumentRepository;
pub use trading_partner_repository::TradingPartnerRepository;

// Re-export backbone-orm types
pub use backbone_orm::repository::{
    DatabaseOperations, PostgresRepository,
    PaginationParams, PaginationInfo, PaginatedResult,
    FilterParams, FilterCondition, SortParams, SortDirection,
};

// Re-export custom persistence types
// <<< CUSTOM
// The hand-written EDI SQL's parameter/projection types (see `edi_document_repository` and
// `trading_partner_repository`, both declared `user_owned` in metaphor.codegen.yaml).
pub use edi_document_repository::{AckRow, DocOutcomeRow, NewInboundDocRow};
pub use trading_partner_repository::NewPartnerRow;
// END CUSTOM
