//! Repository for TradingPartner entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TradingPartner, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::TradingPartner;

/// Table name for TradingPartner entities
pub const TABLE_NAME: &str = "edi.trading_partners";

/// Repository for TradingPartner entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TradingPartnerRepository(
    backbone_orm::GenericCrudRepository<TradingPartner, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TradingPartnerRepository {
    type Target = backbone_orm::GenericCrudRepository<TradingPartner, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TradingPartnerRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(TradingPartnerRepository, TradingPartner, soft_delete);
