//! Repository for TradingPartner entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written TradingPartner SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<TradingPartner, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::TradingPartner;

/// Table name for TradingPartner entities
pub const TABLE_NAME: &str = "edi.trading_partners";

/// Repository for TradingPartner entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct TradingPartnerRepository(
    backbone_orm::GenericCrudRepository<TradingPartner, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for TradingPartnerRepository {
    type Target = backbone_orm::GenericCrudRepository<TradingPartner, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl TradingPartnerRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a partner registration writes.
///
/// Mirrors the raw column shape rather than the `TradingPartner` entity: `format`/`partner_direction`
/// are cast at the DB (`$5::edi_format`, `$6::partner_direction`).
pub struct NewPartnerRow<'a> {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: &'a str,
    pub partner_code: &'a str,
    pub format: &'a str,
    pub partner_direction: &'a str,
}

/// Hand-written TradingPartner SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl TradingPartnerRepository {
    /// Register a trading partner.
    ///
    /// A read/write outside any transaction: takes the pool and runs `execute_scoped` so the RLS fence
    /// (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company))` — the company is
    /// on the DTO, and that scope is what satisfies the INSERT's WITH CHECK fence.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to turn
    /// a duplicate partner code into a domain error.
    pub async fn insert_partner(
        &self,
        pool: &PgPool,
        p: &NewPartnerRow<'_>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO edi.trading_partners
                     (id, company_id, name, partner_code, format, partner_direction, is_active)
                   VALUES ($1,$2,$3,$4,$5::edi_format,$6::partner_direction,true)"#,
            )
            .bind(p.id).bind(p.company_id).bind(p.name).bind(p.partner_code)
            .bind(p.format).bind(p.partner_direction),
        )
        .await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(TradingPartnerRepository, TradingPartner, soft_delete);
