//! Validator for EdiDocument entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<EdiDocument>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::EdiDocument;

/// Validator type alias for EdiDocument entities.
pub type EdiDocumentValidator = EntityValidator<EdiDocument>;

/// Build a validator for EdiDocument with all schema-defined field rules.
pub fn edi_document_validator() -> EdiDocumentValidator {
    EntityValidator::new()
        .rule(RequiredString::new("control_number", |e: &EdiDocument| &e.control_number))
        .rule(RequiredString::new("business_key", |e: &EdiDocument| &e.business_key))
        .rule(RequiredString::new("payload", |e: &EdiDocument| &e.payload))
        .rule(OptionalNotBlank::new("mapped_ref_type", |e: &EdiDocument| e.mapped_ref_type.as_deref()))
        .rule(OptionalNotBlank::new("error_detail", |e: &EdiDocument| e.error_detail.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
