//! Validator for TradingPartner entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<TradingPartner>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::TradingPartner;

/// Validator type alias for TradingPartner entities.
pub type TradingPartnerValidator = EntityValidator<TradingPartner>;

/// Build a validator for TradingPartner with all schema-defined field rules.
pub fn trading_partner_validator() -> TradingPartnerValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &TradingPartner| &e.name))
        .rule(RequiredString::new("partner_code", |e: &TradingPartner| &e.partner_code))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
