//! Auth configuration for EdiDocument handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<EdiDocument>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::EdiDocumentService;
use crate::domain::entity::EdiDocument;

/// Permission string constants for EdiDocument operations.
pub mod permissions {
    pub const LIST:        &str = "edi_document:list";
    pub const READ:        &str = "edi_document:read";
    pub const CREATE:      &str = "edi_document:create";
    pub const UPDATE:      &str = "edi_document:update";
    pub const DELETE:      &str = "edi_document:delete";
    pub const RESTORE:     &str = "edi_document:restore";
    pub const TRASH:       &str = "edi_document:trash";
    pub const EMPTY_TRASH: &str = "edi_document:empty_trash";
    pub const BULK_CREATE: &str = "edi_document:bulk_create";
    pub const UPSERT:      &str = "edi_document:upsert";
}

/// Resource policy for EdiDocument — maps CRUD actions to permission strings.
pub struct EdiDocumentPolicy;

#[async_trait]
impl ResourcePolicy<EdiDocument> for EdiDocumentPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &EdiDocument,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for EdiDocument handlers.
///
/// Wraps `EdiDocumentService` and checks `EdiDocumentPolicy` before delegating.
pub type EdiDocumentGuard = PermissionGuard<EdiDocument>;

/// Service-integrated permission guard for EdiDocument (for use in generated handlers).
pub type EdiDocumentServiceGuard = ServicePermissionGuard<EdiDocument, EdiDocumentService, EdiDocumentPolicy>;

// <<< CUSTOM
// END CUSTOM
