//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod edi_document_auth;
pub mod trading_partner_auth;

pub use edi_document_auth::{EdiDocumentPolicy, EdiDocumentGuard, EdiDocumentServiceGuard};
pub use trading_partner_auth::{TradingPartnerPolicy, TradingPartnerGuard, TradingPartnerServiceGuard};

// <<< CUSTOM
// END CUSTOM
