//! Auth configuration for TradingPartner handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<TradingPartner>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::TradingPartnerService;
use crate::domain::entity::TradingPartner;

/// Permission string constants for TradingPartner operations.
pub mod permissions {
    pub const LIST:        &str = "trading_partner:list";
    pub const READ:        &str = "trading_partner:read";
    pub const CREATE:      &str = "trading_partner:create";
    pub const UPDATE:      &str = "trading_partner:update";
    pub const DELETE:      &str = "trading_partner:delete";
    pub const RESTORE:     &str = "trading_partner:restore";
    pub const TRASH:       &str = "trading_partner:trash";
    pub const EMPTY_TRASH: &str = "trading_partner:empty_trash";
    pub const BULK_CREATE: &str = "trading_partner:bulk_create";
    pub const UPSERT:      &str = "trading_partner:upsert";
}

/// Resource policy for TradingPartner — maps CRUD actions to permission strings.
pub struct TradingPartnerPolicy;

#[async_trait]
impl ResourcePolicy<TradingPartner> for TradingPartnerPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &TradingPartner,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for TradingPartner handlers.
///
/// Wraps `TradingPartnerService` and checks `TradingPartnerPolicy` before delegating.
pub type TradingPartnerGuard = PermissionGuard<TradingPartner>;

/// Service-integrated permission guard for TradingPartner (for use in generated handlers).
pub type TradingPartnerServiceGuard = ServicePermissionGuard<TradingPartner, TradingPartnerService, TradingPartnerPolicy>;

// <<< CUSTOM
// END CUSTOM
