//! EdiDocument API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the EdiDocument CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// EDIDOCUMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for EdiDocument
pub struct EdiDocumentTestData;

impl TestDataGenerator for EdiDocumentTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "partner_id": Uuid::new_v4().to_string(),
            "doc_type": "purchase_order",
            "direction": "inbound",
            "control_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "business_key": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "received",
            "payload": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "mapped_ref_type": null,
            "mapped_ref_id": null,
            "error_detail": null,
            "acknowledged_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "partner_id": Uuid::new_v4().to_string(),
            "doc_type": "purchase_order",
            "direction": "inbound",
            "control_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "business_key": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "status": "received",
            "payload": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "mapped_ref_type": null,
            "mapped_ref_id": null,
            "error_detail": null,
            "acknowledged_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/trading_partners", &super::trading_partner_api_test::TradingPartnerTestData).await {
            deps.push(("partner_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// EDIDOCUMENT API TEST
// ============================================================================

/// EdiDocument API test suite
pub struct EdiDocumentApiTest {
    inner: GenericCrudTest<EdiDocumentTestData>,
}

impl EdiDocumentApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/edi_documents", "EdiDocument");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, EdiDocumentTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for EdiDocumentApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_edi_document_crud() {
        let mut test = EdiDocumentApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add EdiDocument specific tests here
// <<< CUSTOM TESTS END >>>
