//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod edi_document_api_test;
pub mod trading_partner_api_test;

// Re-exports for convenience
pub use crud_test_base::*;
pub use edi_document_api_test::*;
pub use trading_partner_api_test::*;
