//! Edi Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::EdiDocumentService;
use crate::application::service::TradingPartnerService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// EdiDocument service
    pub edi_document_service: Arc<EdiDocumentService>,
    /// TradingPartner service
    pub trading_partner_service: Arc<TradingPartnerService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        edi_document_service: Arc<EdiDocumentService>,
        trading_partner_service: Arc<TradingPartnerService>
    ) -> Self {
        Self {
            edi_document_service,
            trading_partner_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::EdiModule) -> Self {
        Self {
            edi_document_service: module.edi_document_service.clone(),
            trading_partner_service: module.trading_partner_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    edi_document_service: Option<Arc<EdiDocumentService>>,
    trading_partner_service: Option<Arc<TradingPartnerService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the EdiDocument service.
    pub fn with_edi_document_service(mut self, service: Arc<EdiDocumentService>) -> Self {
        self.edi_document_service = Some(service);
        self
    }

    /// Set the TradingPartner service.
    pub fn with_trading_partner_service(mut self, service: Arc<TradingPartnerService>) -> Self {
        self.trading_partner_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            edi_document_service: self.edi_document_service.expect("edi_document_service is required"),
            trading_partner_service: self.trading_partner_service.expect("trading_partner_service is required"),
        }
    }
}
