//! Data Transfer Objects
//!
//! Generated by backbone-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

