//! Public events for Edi module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// EDIDOCUMENT EVENTS
// ============================================================================

/// Event published when a EdiDocument is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EdiDocumentCreatedEvent {
    pub id: EdiDocumentId,
    pub data: EdiDocumentDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EdiDocument is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EdiDocumentUpdatedEvent {
    pub id: EdiDocumentId,
    pub data: EdiDocumentDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a EdiDocument is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EdiDocumentDeletedEvent {
    pub id: EdiDocumentId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// TRADINGPARTNER EVENTS
// ============================================================================

/// Event published when a TradingPartner is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradingPartnerCreatedEvent {
    pub id: TradingPartnerId,
    pub data: TradingPartnerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TradingPartner is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradingPartnerUpdatedEvent {
    pub id: TradingPartnerId,
    pub data: TradingPartnerDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a TradingPartner is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradingPartnerDeletedEvent {
    pub id: TradingPartnerId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Edi module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum EdiEvent {
    EdiDocumentCreated(EdiDocumentCreatedEvent),
    EdiDocumentUpdated(EdiDocumentUpdatedEvent),
    EdiDocumentDeleted(EdiDocumentDeletedEvent),
    TradingPartnerCreated(TradingPartnerCreatedEvent),
    TradingPartnerUpdated(TradingPartnerUpdatedEvent),
    TradingPartnerDeleted(TradingPartnerDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EdiEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for EdiEventMetadata {
    fn default() -> Self {
        Self {
            module: "edi",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
