//! Edi Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Edi exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use edi::exports::{EdiDocumentDto, EdiQueryService};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `EdiDocumentDto` - Data transfer object for EdiDocument
/// - `EdiDocumentSummary` - Summary view of EdiDocument
/// - `EdiDocumentId` - Type-safe ID wrapper
/// - `TradingPartnerDto` - Data transfer object for TradingPartner
/// - `TradingPartnerSummary` - Summary view of TradingPartner
/// - `TradingPartnerId` - Type-safe ID wrapper
///
/// ## Public Services
/// - `EdiQueryService` - Read-only queries
///
/// ## Public Events
/// - `EdiDocumentCreatedEvent` - Published when EdiDocument is created
/// - `EdiDocumentUpdatedEvent` - Published when EdiDocument is updated
/// - `EdiDocumentDeletedEvent` - Published when EdiDocument is deleted
/// - `TradingPartnerCreatedEvent` - Published when TradingPartner is created
/// - `TradingPartnerUpdatedEvent` - Published when TradingPartner is updated
/// - `TradingPartnerDeletedEvent` - Published when TradingPartner is deleted
pub struct ExportSummary;
