//! Public services for Edi module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These services provide the public API for other modules.
//! They only expose read operations - writes go through events.

use std::sync::Arc;

use anyhow::Result;
use async_trait::async_trait;
use uuid::Uuid;

use super::types::*;

// ============================================================================
// QUERY SERVICE TRAIT
// ============================================================================

/// Public query service for Edi module
///
/// This trait defines read-only operations that other modules can use.
/// Implementations should NOT expose internal domain logic.
#[async_trait]
pub trait EdiQueryService: Send + Sync {
    /// Get EdiDocument by ID
    async fn get_edi_document(&self, id: EdiDocumentId) -> Result<Option<EdiDocumentDto>>;

    /// Get EdiDocument summary by ID
    async fn get_edi_document_summary(&self, id: EdiDocumentId) -> Result<Option<EdiDocumentSummary>>;

    /// Check if EdiDocument exists
    async fn edi_document_exists(&self, id: EdiDocumentId) -> Result<bool>;

    /// Get TradingPartner by ID
    async fn get_trading_partner(&self, id: TradingPartnerId) -> Result<Option<TradingPartnerDto>>;

    /// Get TradingPartner summary by ID
    async fn get_trading_partner_summary(&self, id: TradingPartnerId) -> Result<Option<TradingPartnerSummary>>;

    /// Check if TradingPartner exists
    async fn trading_partner_exists(&self, id: TradingPartnerId) -> Result<bool>;

}

// ============================================================================
// QUERY SERVICE IMPLEMENTATION
// ============================================================================

/// Default implementation of EdiQueryService
pub struct EdiQueryServiceImpl<R> {
    repository: Arc<R>,
}

impl<R> EdiQueryServiceImpl<R> {
    pub fn new(repository: Arc<R>) -> Self {
        Self { repository }
    }
}

// ============================================================================
// CUSTOM SERVICES
// ============================================================================

// <<< CUSTOM SERVICES START >>>
// Add custom public services here
// <<< CUSTOM SERVICES END >>>
