//! Edi Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::EdiDocumentService;
pub use application::service::TradingPartnerService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Edi module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let edi = EdiModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = edi.all_crud_routes();
/// ```
pub struct EdiModule {
    pub edi_document_service: Arc<EdiDocumentService>,
    pub trading_partner_service: Arc<TradingPartnerService>,
}

impl EdiModule {
    /// Create a new module builder
    pub fn builder() -> EdiModuleBuilder {
        EdiModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_edi_document_routes,
            create_trading_partner_routes,
        };

        Router::new()
            .merge(create_edi_document_routes(self.edi_document_service.clone()))
            .merge(create_trading_partner_routes(self.trading_partner_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for EdiModule
pub struct EdiModuleBuilder {
    db_pool: Option<PgPool>,
}

impl EdiModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<EdiModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // EdiDocument service
        let edi_document_repository = Arc::new(EdiDocumentRepository::new(db_pool.clone()));
        let edi_document_service = Arc::new(EdiDocumentService::with_repository(edi_document_repository.clone()));

        // TradingPartner service
        let trading_partner_repository = Arc::new(TradingPartnerRepository::new(db_pool.clone()));
        let trading_partner_service = Arc::new(TradingPartnerService::with_repository(trading_partner_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(EdiModule {
            edi_document_service,
            trading_partner_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for EdiModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
