//! Use case type aliases for EdiDocument aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateEdiDocumentDto, UpdateEdiDocumentDto};
use crate::application::service::EdiDocumentService;
use crate::domain::entity::EdiDocument;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateEdiDocumentUseCase = CreateUseCase<EdiDocument, CreateEdiDocumentDto, EdiDocumentService>;
pub type UpdateEdiDocumentUseCase = UpdateUseCase<EdiDocument, UpdateEdiDocumentDto, EdiDocumentService>;
pub type GetEdiDocumentUseCase    = GetUseCase<EdiDocument, EdiDocumentService>;
pub type DeleteEdiDocumentUseCase = DeleteUseCase<EdiDocument, EdiDocumentService>;
pub type ListEdiDocumentUseCase   = ListUseCase<EdiDocument, EdiDocumentService>;

// <<< CUSTOM
// END CUSTOM
