//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod edi_document_usecases;
pub mod trading_partner_usecases;

pub use edi_document_usecases::{
    CreateEdiDocumentUseCase, UpdateEdiDocumentUseCase, GetEdiDocumentUseCase,
    DeleteEdiDocumentUseCase, ListEdiDocumentUseCase,
};
pub use trading_partner_usecases::{
    CreateTradingPartnerUseCase, UpdateTradingPartnerUseCase, GetTradingPartnerUseCase,
    DeleteTradingPartnerUseCase, ListTradingPartnerUseCase,
};

// <<< CUSTOM
// END CUSTOM
