//! Use case type aliases for TradingPartner aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateTradingPartnerDto, UpdateTradingPartnerDto};
use crate::application::service::TradingPartnerService;
use crate::domain::entity::TradingPartner;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateTradingPartnerUseCase = CreateUseCase<TradingPartner, CreateTradingPartnerDto, TradingPartnerService>;
pub type UpdateTradingPartnerUseCase = UpdateUseCase<TradingPartner, UpdateTradingPartnerDto, TradingPartnerService>;
pub type GetTradingPartnerUseCase    = GetUseCase<TradingPartner, TradingPartnerService>;
pub type DeleteTradingPartnerUseCase = DeleteUseCase<TradingPartner, TradingPartnerService>;
pub type ListTradingPartnerUseCase   = ListUseCase<TradingPartner, TradingPartnerService>;

// <<< CUSTOM
// END CUSTOM
