//! HTTP handlers
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod edi_document_handler;
pub mod trading_partner_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use edi_document_handler::{create_edi_document_routes, create_edi_document_read_routes, create_edi_document_write_routes};
pub use trading_partner_handler::{create_trading_partner_routes, create_trading_partner_read_routes, create_trading_partner_write_routes};
// <<< CUSTOM
// END CUSTOM
